-- core 
require("core.init")

--plugins
require("plugins.alpha")
require("plugins.autopairs")
require("plugins.cmp")
require("plugins.colorscheme")
require("plugins.dressing")
require("plugins.indent-blankline")
require("plugins.lsp")
require("plugins.lspKeycaps")
require("plugins.lualine")
require("plugins.mason")
require("plugins.miniIcons")
require("plugins.neotree")
require("plugins.noice")
require("plugins.snacks")
require("plugins.telescope")
require("plugins.todo-comments")
require("plugins.treesitter")
require("plugins.trouble")
require("plugins.ts-comments")
require("plugins.whichkey")
require("plugins.MarkDown")
require("plugins.lazygit")
